Expose PAPI's optional "billing_tag" field, and fix inability to empty fields
TritonDataCenter/sdc-adminui pull request #270
Opened 2023-07-27 16:42 UTC by marsell

PAPI has an [optional "billing_tag" field](https://github.com/TritonDataCenter/sdc-papi/blob/master/docs/index.md#package-billing_tag) that is currently only accessible from the CLI. This change adds support for creating a package with billing tag text, and editing billing tags in packages later on.

It also fixes an annoying problem with the package update page (when you click "Modify Package" while viewing an existing package; _why is there no URL for this waaaargh_ 😜), which makes it impossible to delete a string. For example, if a description field contains the text "foo", and you'd rather it was blank, deleting "foo" in the package update page and saving the package won't do what you expect: the "foo" remains. This broken behaviour, and the fix in this patch, has been verified by checking sdc-papi /packages/<uuid> from the CLI.

2023-08-22 14:54 UTC, marsell commented
With new changes:

![1](https://github.com/TritonDataCenter/sdc-adminui/assets/144988/74c1395b-ee85-4399-9e7d-3f8f87e3c029)
![2](https://github.com/TritonDataCenter/sdc-adminui/assets/144988/8d573cc8-2d9f-407b-b897-3653b09fece4)

2023-08-22 18:03 UTC, travispaul requested changes
@marsell could you bump the package.json to 1.4.0 too? Thanks!

2023-08-23 04:09 UTC, marsell commented
Updated to 1.4.0.

2023-08-23 14:01 UTC, travispaul approved these changes

2023-08-24 08:37 UTC, marsell commented
bahamat requested that empty strings be removed from packages. Done.

2023-08-24 23:53 UTC, bahamat approved these changes

2023-08-24 23:59 UTC, merged